apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deployment
  labels:
    app: simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name:  simple-webapp
        image: vaibhavrawat/simple-webapp
        ports:
        - containerPort: 3000
        # envFrom:
        # - secretRef:
        #     name: dotfile-secret

      
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
spec:
  type: NodePort
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001